/* Generated by j4_gen.c */
#include <stdio.h>

const int VALS[] = {34,71,83,95,107,119,130,142,154,166,178,201,213,225,237,260,272,284,296,331,343,355,390,402,414,461,473,520,532,591,671,};
const int VALS_LEN = sizeof(VALS) / sizeof(VALS[0]);

int main(void) {
    int d;
    scanf("%d", &d);
    int days = d / (60 * 12), mins = d % (60 * 12);
    int res = VALS_LEN * days;
    for (int i = 0; i < VALS_LEN; i++) {
        if (VALS[i] > mins) {
            break;
        }
        res++;
    }
    printf("%d\n", res);
}
